[project]
name = "keymouselogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auto-py-to-exe>=2.46.0",
    "pyinstaller>=6.14.2",
    "pynput>=1.8.1",
    "pyqt6>=6.9.1",
]
